var nombre = "Pedro";


//AMBITO DE BLOQUE
if(true){
    //VAR SE SALE DE ESTE BLOQUE Y PERMITE LA REDECLARACIÓN, ELIMINADO EL CONTENIDO DE LA VARIBLE CON EL MISMO DECLARA ANTERIORMENTE
    var nombre = "Carlos";
}

